<option selected disabled value="">--- Pilih ---</option>
<option value="- N/A -">- N/A -</option>
<option value="ALBERT">ALBERT</option>
<option value="AXEL">AXEL</option>
<option value="CALVIN">CALVIN</option>
<option value="CHALVIN">CHALVIN</option>
<option value="CHILWIN">CHILWIN</option>
<option value="CRISYE">CRISYE</option>
<option value="DAVID">DAVID</option>
<option value="DAVIN">DAVIN</option>
<option value="DHARMA">DHARMA</option>
<option value="ERIC">ERIC</option>
<option value="EVAN">EVAN</option>
<option value="FILBERT">FILBERT</option>
<option value="JAEDEN">JAEDEN</option>
<option value="JOEL">JOEL</option>
<option value="JONG">JONG</option>
<option value="JOVREDO">JOVREDO</option>
<option value="MERVIN">MERVIN</option>
<option value="MORGERTZ">MORGERTZ</option>
<option value="NUGROHO">NUGROHO</option>
<option value="ORLANDO">ORLANDO</option>
<option value="RICHARD">RICHARD</option>
<option value="RITCHIE">RITCHIE</option>
<option value="SHAWN">SHAWN</option>
<option value="WILBERT">WILBERT</option>
<option value="WILSON">WILSON</option>
<option value="YOHANES">YOHANES</option>