<option selected disabled value="">--- Pilih ---</option>
<option value="- N/A -">- N/A -</option>
<option value="ADRINA">ADRINA</option>
<option value="ANGELICA">ANGELICA</option>
<option value="ANGELINE">ANGELINE</option>
<option value="CARYN">CARYN</option>
<option value="CATHERINE">CATHERINE</option>
<option value="CELINE">CELINE</option>
<option value="CHARISSE">CHARISSE</option>
<option value="CRESTELLA">CRESTELLA</option>
<option value="EARLEANE">EARLEANE</option>
<option value="EUQENE">EUQENE</option>
<option value="FELICE">FELICE</option>
<option value="GRACE">GRACE</option>
<option value="HARVANY">HARVANY</option>
<option value="IRENE">IRENE</option>
<option value="JANE">JANE</option>
<option value="KHELLY">KHELLY</option>
<option value="MARGARETH">MARGARETH</option>
<option value="NADIA">NADIA</option>
<option value="NIKITA">NIKITA</option>
<option value="NOVRICIELLA">NOVRICIELLA</option>
<option value="SHANA">SHANA</option>
<option value="WINNIE">WINNIE</option>